version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/static/videos:/app/app/static/videos
      - ./app/static/documentos:/app/app/static/documentos
